SRM_dataset_cfg:
  name: mnist_sudoku_lazy
  root: ./datasets/mnist_sudoku/
  image_shape: [252, 252]
  pad_to_size:
  - 288
  - 288
  adjust_with_resize: true
  resize_mode: bicubic
  resize_antialias: true
  subset_size: null
  top_n: 1000
  test_samples_num: 10000
  augment: false
  grayscale: true
  reveal_cells: [[5,5],[1,1]]
SRM_conditioning_cfg:
  label: false
  mask: false